# --------------------------------------------------------------------------- #
# Script: combine_r_scripts.R
#
# Description:
# This script scans a specified source directory for all files ending with the
# .R or .r extension. It then reads each of these files and concatenates their
# content into a single output file. Each code block from the original files
# is clearly demarcated with a header and footer for easy navigation.
#
# Usage:
# 1. Set the 'source_directory' variable to the path of your R scripts.
# 2. Set the 'output_file_path' variable to where you want to save the combined file.
# 3. Run the script.
#
# --------------------------------------------------------------------------- #

# --- Configuration ---

# 1. Set the directory containing the R scripts you want to combine.
#    Use "." for the current working directory.
source_directory <- "./R/"

# 2. Set the name and path for the combined output R file.
output_file_path <- "combined_improveR_presentation_code.R"

# --- Main Logic ---

# Get a list of all .R files (case-insensitive) in the source directory
# The `$` ensures we only match files that END with .R
# `full.names = TRUE` gives us the full path to each file.
r_files <- list.files(
  path = source_directory,
  pattern = "\\.R$",
  full.names = TRUE,
  ignore.case = TRUE,
  recursive = TRUE # Set to TRUE if you want to search in subdirectories as well
)

# Exclude the output file itself if it's in the same directory and already exists
# This prevents the script from appending itself to the output on subsequent runs.
r_files <- r_files[!grepl(basename(output_file_path), r_files, fixed = TRUE)]


# Check if any R files were found
if (length(r_files) == 0) {
  stop("No .R files found in the specified directory: '", source_directory, "'")
}

# Announce the start of the process
cat("Found", length(r_files), "R files to combine.\n")
cat("Output will be written to:", output_file_path, "\n\n")

# Open a connection to the output file for writing.
# Using a connection and closing it is safer than repeated appends.
out_conn <- file(output_file_path, "w")

# Use on.exit to ensure the file connection is closed, even if an error occurs.
on.exit(close(out_conn), add = TRUE)

# Write a header for the combined file
header_text <- paste(
  "# --------------------------------------------------------------------------- #",
  "# This file was automatically generated by combine_r_scripts.R",
  paste("# Date:", Sys.time()),
  paste("# Total files combined:", length(r_files)),
  "# --------------------------------------------------------------------------- #\n\n",
  sep = "\n"
)
writeLines(header_text, con = out_conn)


# Loop through each R file, read its content, and write to the output file
for (file_path in r_files) {

  file_name <- basename(file_path)
  cat("Processing:", file_name, "...\n")

  # Create a header for this specific file's content
  file_header <- paste(
    "\n\n# =========================================================================== #",
    paste("# START OF FILE:", file_name),
    "# =========================================================================== #\n",
    sep = "\n"
  )

  # Read the content of the current R file
  file_content <- readLines(file_path, warn = FALSE)

  # Create a footer
  file_footer <- paste(
    "\n# =========================================================================== #",
    paste("# END OF FILE:", file_name),
    "# =========================================================================== #\n",
    sep = "\n"
  )

  # Write the header, content, and footer to the output connection
  writeLines(file_header, con = out_conn)
  writeLines(file_content, con = out_conn)
  writeLines(file_footer, con = out_conn)
}

# Announce completion
cat("\nSuccessfully combined all R scripts into:", output_file_path, "\n")
