$PROB Model 1

$INPUT ID AMT EVID TIME CONC=DV
$DATA example-new.dat IGNORE=I
$SUBROUTINE ADVAN2 TRANS2

$PK
  KA=THETA(1)*EXP(ETA(1))
  CL=THETA(2)*EXP(ETA(2))
  V=THETA(3)*EXP(ETA(3))
  S2=V/1000

$ERROR
  W=F*THETA(4)
  IF (F.GT.0) THEN
     Y=F+W*EPS(1)
     IPRED=F
     IRES=DV-IPRED
     IWRES=IRES/W
  ELSE
     Y=0
     IPRED=0
     IRES=0
     IWRES=0
  ENDIF

$THETA
  (0, 2.0) ;1 KA
  (0, 10.) ;2 CL
  (0, 100) ;3 V
  (0, 0.3) ;4 SIGMA

$OMEGA DIAGONAL(3)
  0.25 ; VAR(KA)
  0.09 ; VAR(CL)
  0.16 ; VAR(V)

$SIGMA DIAGONAL(1)
  1 FIX

$EST MAXEVAL=9000 PRINT=5 METHOD=1 INTERACTION
$COV PRINT=E
$TABLE ID AMT EVID TIME IPRED IWRES NOPRINT ONEHEADER FILE=model1.fit
