structure(list(url = "http://envhost1.hc.scintecodev.internal:5310/repository/api/v1/resources/envhost1.hc.scintecodev.internal-5310:FO-54947", 
    status_code = 404L, headers = structure(list(`access-control-allow-origin` = "*", 
        `access-control-allow-credentials` = "true", `access-control-allow-headers` = "origin, content-type, accept, authorization", 
        `access-control-allow-methods` = "GET, POST, PUT, DELETE, OPTIONS, HEAD", 
        authorization = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuU0tfTEwyXy1QbnBXbVNKU2VYUnFFLUF4MlZ3bVkyZ05OREZCdEpBb0FzIn0.eyJleHAiOjE3NDcxNDAwOTEsImlhdCI6MTc0NzEzOTc5MSwiYXV0aF90aW1lIjoxNzQ3MTM0NTE1LCJqdGkiOiIxYTBjNDIzMi0yMzdkLTRjYjgtODJjZS05MDA1ZjhiZTM4YWYiLCJpc3MiOiJodHRwczovLzUzNzEuZW52aG9zdDEuaGMuc2NpbnRlY28uY29tOjE0NDMvcmVhbG1zL2ltcHJvdmUiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiODdiZjg2ZjEtNTU1Mi00MTMxLWI0MTMtNDE0Y2ExYjhjMWMxIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiaW1wcm92ZS1hcGktY2xpZW50Iiwic2lkIjoiODYyZGI0MTUtZjk2Mi00MzNlLWE3NDQtMDZlMThmNDBiODY2IiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyIvKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1pbXByb3ZlIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIn0.IGHEBUoiOqD-Dd010gH60Et4aVlb0jO9O59AGMACCF7kaJBc-Q5zawdBNKw6dVyw5_U9fuTt0bZY_S15CnJPL8dtd_ghZXXTnxzh2EraDzINmgwLNC9z5x5xg5cOmAvTHLB5G3g4ooVoBnt-oxT20l0GwdTj2EVdHsw3DyVOdOWpc_Zbp3uEFKizuAxjX20IQIdMbhb7OAl6jdcUvDPyteoLlAVKWABTe-cQRVVNu_TcD8eOvWPbo-rw0CYTgxpmHH8hoOQKYpLivtFyfvlJJ8wWS9sBxqkpbzgXK_Lt9LzacrmgOIPhXvrshr5m_vIZxUGXXW_U_DuqMGfz0KRHSg", 
        `content-type` = "application/json", `content-length` = "56", 
        date = "Tue, 13 May 2025 12:36:31 GMT"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`access-control-allow-origin` = "*", 
            `access-control-allow-credentials` = "true", `access-control-allow-headers` = "origin, content-type, accept, authorization", 
            `access-control-allow-methods` = "GET, POST, PUT, DELETE, OPTIONS, HEAD", 
            authorization = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuU0tfTEwyXy1QbnBXbVNKU2VYUnFFLUF4MlZ3bVkyZ05OREZCdEpBb0FzIn0.eyJleHAiOjE3NDcxNDAwOTEsImlhdCI6MTc0NzEzOTc5MSwiYXV0aF90aW1lIjoxNzQ3MTM0NTE1LCJqdGkiOiIxYTBjNDIzMi0yMzdkLTRjYjgtODJjZS05MDA1ZjhiZTM4YWYiLCJpc3MiOiJodHRwczovLzUzNzEuZW52aG9zdDEuaGMuc2NpbnRlY28uY29tOjE0NDMvcmVhbG1zL2ltcHJvdmUiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiODdiZjg2ZjEtNTU1Mi00MTMxLWI0MTMtNDE0Y2ExYjhjMWMxIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiaW1wcm92ZS1hcGktY2xpZW50Iiwic2lkIjoiODYyZGI0MTUtZjk2Mi00MzNlLWE3NDQtMDZlMThmNDBiODY2IiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyIvKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1pbXByb3ZlIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIn0.IGHEBUoiOqD-Dd010gH60Et4aVlb0jO9O59AGMACCF7kaJBc-Q5zawdBNKw6dVyw5_U9fuTt0bZY_S15CnJPL8dtd_ghZXXTnxzh2EraDzINmgwLNC9z5x5xg5cOmAvTHLB5G3g4ooVoBnt-oxT20l0GwdTj2EVdHsw3DyVOdOWpc_Zbp3uEFKizuAxjX20IQIdMbhb7OAl6jdcUvDPyteoLlAVKWABTe-cQRVVNu_TcD8eOvWPbo-rw0CYTgxpmHH8hoOQKYpLivtFyfvlJJ8wWS9sBxqkpbzgXK_Lt9LzacrmgOIPhXvrshr5m_vIZxUGXXW_U_DuqMGfz0KRHSg", 
            `content-type` = "application/json", `content-length` = "56", 
            date = "Tue, 13 May 2025 12:36:31 GMT"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"status\" : 404,\n  \"message\" : \"HTTP 404 Not Found\"\n}"), 
    date = structure(1747139791, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 7.3e-05, 
    connect = 0.020726, pretransfer = 0.020932, starttransfer = 0.093285, 
    total = 0.09341)), class = "response")
