structure(list(url = "http://envhost2.hc.scintecodev.internal:18118/repository/api/v1/users", 
    status_code = 401L, headers = structure(list(`access-control-allow-origin` = "*", 
        `access-control-allow-credentials` = "true", `access-control-allow-headers` = "origin, content-type, accept, authorization", 
        `access-control-allow-methods` = "GET, OPTIONS, HEAD, PUT, POST", 
        responsetype = "serverError", errormessage = "(reqId: ): 223e50dc-1cb9-44f1-8a5f-83516c28b710 Token could not be verified", 
        errortype = "AuthenticationError", `content-type` = "text/html;charset=utf-8", 
        `content-language` = "en", `content-length` = "808", 
        date = "Thu, 20 Mar 2025 16:11:13 GMT"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(`access-control-allow-origin` = "*", 
            `access-control-allow-credentials` = "true", `access-control-allow-headers` = "origin, content-type, accept, authorization", 
            `access-control-allow-methods` = "GET, OPTIONS, HEAD, PUT, POST", 
            responsetype = "serverError", errormessage = "(reqId: ): 223e50dc-1cb9-44f1-8a5f-83516c28b710 Token could not be verified", 
            errortype = "AuthenticationError", `content-type` = "text/html;charset=utf-8", 
            `content-language` = "en", `content-length` = "808", 
            date = "Thu, 20 Mar 2025 16:11:13 GMT"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<!doctype html><html lang=\"en\"><head><title>HTTP Status 401 – Unauthorized</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1><hr class=\"line\" /><p><b>Type</b> Status Report</p><p><b>Message</b> AuthenticationError&#47;(reqId: ): 223e50dc-1cb9-44f1-8a5f-83516c28b710 Token could not be verified</p><p><b>Description</b> The request has not been applied to the target resource because it lacks valid authentication credentials for that resource.</p><hr class=\"line\" /><h3>Apache Tomcat/8.5.100</h3></body></html>"), 
    date = structure(1742487073, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.026722, 
    connect = 0.047355, pretransfer = 0.047505, starttransfer = 0.099622, 
    total = 0.099681)), class = "response")
